### ISSUE TITLE
PTR 

### ISSUE THREAD

**Issue by dawnn07** [nodemailer/wildduck#704] opened 2024-07-11 09:34 UTC
Make sure that your public IP has a PTR record set to mail.lubanlock.online.
If your hosting provider does not allow you to set PTR records but has
assigned their own hostname, then edit /etc/zone-mta/pools.toml and replace
the hostname mail.lubanlock.online with the actual hostname of this server.

Anyone know how to set this ?

**Comment by louis-lau** [comment] 2024-07-11 09:38
Duplicate of #701. Already answered this, you need to contact the owner of the ip for info on how to change it.

**Closed by louis-lau** 2024-07-11 09:38 UTC
