### ISSUE TITLE
Won't send emails

### ISSUE THREAD

**Issue by LoganHeinzelman** [nodemailer/wildduck#131] opened 2019-05-17 03:20 UTC
I set a PTR record. I did all the other stuff and i still cant send emails. i can receive them fine. All i get is message was queued for delivery

**Comment by WheresTheSugar** [comment] 2019-06-01 05:33
Having the same issue :(

**Comment by rqelibari** [comment] 2019-06-08 00:03
@Loganrose and @WheresTheSugar The information you provided is only sufficient to tell that your email service is not working and that the reason could be anything.
If you want people to help you find the real problem, you need to provide a lot more information. E.g. in this case:

- What installation procedure did you follow?
- What exactly did you install?
- Which SMTP software is supposed to send the email? Is it connected to Wildduck IMAP?
- What does the log say? How did you obtain the message: 'message was queued for delivery'? Was there anything else in the log?

**Comment by WheresTheSugar** [comment] 2019-06-08 00:08
In my case I went through [this entire install script](https://github.com/nodemailer/wildduck/tree/master/setup) on a fresh Ubuntu 16.04 and it didn't install an MTA or start it up. Also redis doesn't startup automatically and needs to be added to the list of enabled daemons in systemctl.

**Comment by rqelibari** [comment] 2019-06-08 00:14
How did you ran those scripts? I am asking because the MTA should be installed in script [09_install_zone_mta.sh](https://github.com/nodemailer/wildduck/blob/master/setup/09_install_zone_mta.sh) and activated in script [14_install_start_services.sh](https://github.com/nodemailer/wildduck/blob/master/setup/14_install_start_services.sh) if executed correctly.

**Comment by WheresTheSugar** [comment] 2019-06-08 00:16
@rqelibari `./install example.com mail.example.com` but yea, no smtp and I tried looking for zone mta and it doesn't seem to be on there? What should it's service file be called?

**Comment by rqelibari** [comment] 2019-06-08 00:19
> `./install example.com mail.example.com`

That should usually do it, so there has to be some kind of issue here. How did you download the files?
The ZoneMTA service file should be located at `/etc/systemd/system/zone-mta.service`. Is there any file on your system?

**Comment by WheresTheSugar** [comment] 2019-06-08 00:19
@rqelibari actually, just checked it out and zone-mta wasn't started. it was also in a failed state with no logs available however starting it has fixed my issue all together.

**Comment by WheresTheSugar** [comment] 2019-06-08 00:21
Had to `systemctl enable zone-mta` for reboot as well it seems. but 2nd reboot took fine.

**Comment by rqelibari** [comment] 2019-06-09 23:37
@andris9 I think you can close this issue now. WheresTheSugar's problem is resolved and Loganrose is not answering and maybe does not have the issue anymore. What do you think?

**Comment by Loganrose** [comment] 2019-06-09 23:39
I'm currently not able to try the fix as my ISP is being less than nice.

**Comment by Loganrose** [comment] 2019-06-10 00:32
Ok zone-mta is the issue. It wasnt automatically starting and neither was
redis.

**Comment by andris9** [comment] 2019-06-10 07:38
Usually when zone-mta does not start then the machine already has a SMTP service installed, for example Postfix. Apparmor might also mess up some things. "Fresh" Ubuntu VPS means different things for different hosting providers, WildDuck installer is tested in DigitalOcean.

**Comment by furkankinyas** [comment] 2019-12-09 21:35
Digitalocean Fresh Ubuntu 18.04 LTS
Scripted install
i have same problem after reboot.
smtp dont work and redis dont start.
my solution is
$redis-server&
$systemctl restart zone-mta
$systemctl restart wildduck

**Comment by louis-lau** [comment] 2020-09-13 23:29
Duplicate of #112

**Closed by louis-lau** 2020-09-13 23:29 UTC
