### ISSUE TITLE
API update massive forwards all users

### ISSUE THREAD

**Issue by Bianconiglio** [nodemailer/wildduck#289] opened 2020-11-17 17:00 UTC
Hi,
there is a method for update massive all users with api?

for one user for update forwards i use:

curl -i -XPUT http://localhost:8080/users/idofuser \
-H 'Content-type: application/json' \
-d '{
  "forwards": 15
}'

but for do this update for all users in database?

**Comment by louis-lau** [comment] 2020-11-17 17:02
Duplicate of #178

**Closed by louis-lau** 2020-11-17 17:02 UTC
