### ISSUE TITLE
Api typescript definitions

### ISSUE THREAD

**Issue by ramiroaisen** [nodemailer/wildduck#197] opened 2020-04-11 17:45 UTC
Hi!
Is somewhere available typescript definitions for the api
if not i can write them and make a PR,
I cant find the change stream definition in the api.wildduck.email page, where can i find it?

**Comment by louis-lau** [comment] 2020-04-11 17:48
Seems like a duplicate of #179. API clients with typescript definitions could be generated if there was an OpenApi definition 😁.

**Comment by louis-lau** [comment] 2020-09-13 23:50
Duplicate of #179

**Closed by louis-lau** 2020-09-13 23:50 UTC

**Comment by louis-lau** [comment] 2020-11-18 14:27
@ramiroaisen Wildduck now has an openapi spec. You can sue this spec to generate typescript definitions for the api :)
