### ISSUE TITLE
API for uploading certificates

### ISSUE THREAD

**Issue by louis-lau** [nodemailer/wildduck#149] opened 2019-09-26 02:04 UTC
Was looking into the possibility of SNI with Wildduck and ZoneMTA. It seems possible to pass sniOptions in the imap/pop3 tls config, as well as in the additional smtp-server options in ZoneMTA. I'm not very clear on what the exact format of that config would be though.

I've gotten as far as that it's a map of servernames and TLS options, but not completely sure what TLS options mean and how I could point that to a certificate/key file.

I'm honestly really impressed by WildDuck and ZoneMTA!

**Comment by andris9** [comment] 2019-09-26 07:04
SNI support is something that may or may not be there - I don't know. I tried to get SNI included when I started with WildDuck and ZoneMTA but later did not needed it, so kept it as it was at that time. 

`sniOptions` minimally includes `cert` and `key` as strings and it probably should look like this in the imap.toml config file (did not test, so might not work):

```
[tls.sniOptions."example.com"]
key="-----BEGIN RSA PRIVATE KEY-....",
cert="-----BEGIN CERTIFICATE-...."
```

Instead of SNI I started using Lets Encrypt certs with multiple DNS names. Alternatively you could use something like HAProxy that would handle TLS and then set up WildDuck without TLS. Should be also possible to do the same with ZoneMTA.

<img width="491" alt="Screenshot 2019-09-26 at 10 00 27" src="https://user-images.githubusercontent.com/132242/65665742-ebcd2980-e044-11e9-9113-7dfb1eef0aeb.png">

**Comment by louis-lau** [comment] 2019-09-26 10:09
We need SNI because we want to give everyone the ability to use mail.domain.com. I looked into nginx for proxying but it didn't seem to support SNI. I didn't even think about haproxy. But looking at it it seems haproxy does support TLS, but not STARTTLS. Which makes sense. 

I'll have to try sniOptions first. If it doesn't work we can always offer everyone mail.domain.com without STARTTLS. Will let you know how it works out. Thank you!

**Comment by andris9** [comment] 2019-09-26 11:00
I wrote a blog post about using Haproxy in front of WildDuck a while ago: https://blog.nodemailer.com/2017/10/12/building-fault-tolerant-email-storage-for-30-a-month/

The setup described in the post did not actually work as there was not enough RAM for MongoDB.

**Comment by louis-lau** [comment] 2019-09-26 11:14
That was a good read. I see you handled TLS termination at haproxy as well. 
I've only read the documentation, but am I correct when I say that STARTTLS would not be supported? Or did WildDuck have the correct certs as well in your case?

**Comment by andris9** [comment] 2019-09-26 12:41
This setup would not support STARTTLS, so your system would only support port 993 for IMAP, port 995 for POP3 and port 465 for SMTP (which is now a [standard SMTP port](https://tools.ietf.org/html/rfc8314#section-3.3)). HAProxy would manage everything related to TLS. WildDuck / ZoneMTA would run on cleartext mode (or using some cert for TLS that is supported by the HAProxy server if you don't want to use cleartext).

**Comment by louis-lau** [comment] 2019-09-26 17:07
Right, got it. Thank you!

**Comment by louis-lau** [comment] 2019-09-28 13:03
Just wanted to confirm this does work!
Had to use toml multi-line basic strings like so:
```
[tls.sniOptions."example.com"]
cert="""
-----BEGIN CERTIFICATE-----
blabla
-----END CERTIFICATE-----
"""

key="""
-----BEGIN RSA PRIVATE KEY-----
blabla
-----END RSA PRIVATE KEY-----
"""
```

**Comment by andris9** [comment] 2019-09-28 15:48
Great! Maybe try some load testing as well as I remember that there might have been some memory leak stuff happening around SNI. This may have been caused by node itself though as the year was 2015 or so and a lot has changed since.

**Comment by andris9** [comment] 2019-09-29 08:52
One idea that I had with SNI and maybe should start working on it again was dynamic certificates pushed via API. So instead of storing certificate files on disk you would call an API endpoint (similar to DKIM) where you provide the cert and the key for some specific domain name. And when clients make connections against the server using that server name, then SNI handler would look up key and cert from database.

**Comment by louis-lau** [comment] 2019-09-29 10:40
That's a great idea! I was already thinking about how I would get the certificates in the config automatically and how I would deploy it across multiple instances.

One thing though, ZoneMTA would need to use them as well. Not sure of that's possible for the wildduck plugin?

**Comment by andris9** [comment] 2019-09-29 11:02
I think it would be possible to get it working both for WildDuck and ZoneMTA. Some time ago I worked on dynamic certificate reloading where you could go with "systemctl reload wildduck|zone-mta" and it would reload certificates without closing existing connections. It turned out unnecessary feature (as I restart services so often to upgrade that certificates never expire before next restart) and it does not work anymore (don't know why, probably some regression bug). Anyway - both can (or can be modified to) support dynamic certificate loading and it does not matter if the certs are loaded from disk or from database. Historically, loading from disk is also for security reasons (you can apply file owner user and groups) but there is no technical reason why you should load certs from disk and not from db.

**Comment by louis-lau** [comment] 2019-09-29 12:53
That would be pretty cool, and make things a lot more polished. Not to mention easier for me as well 😁.

Reopening the issue in that case.

**Comment by andris9** [comment] 2021-05-13 14:26
@louis-lau first draft of using SNI is now available. Right now only IMAP/POP3 are supported, ZoneMTA support will come a bit later as it's TLS stack needs a bit of changes first.

Certificate management API docs can be found [here](https://docs.wildduck.email/api/#tag/Certs) (applies to the latest master branch)

**Comment by louis-lau** [comment] 2021-05-13 18:39
Very nice! Just some thoughts in no particular order:

Are you planning to reuse some of https://github.com/andris9/https-front, to provide built in (on demand) let's encrypt?

Maybe there could be a script that imports certs from a file directory as well, to provide an easier integration path with existing acme clients.

Example values would be helpful in the openapi spec, especially for the cert and privateKey values. They'd appear on the right in ReDoc, instead of `"string"`.

Since there can only be a single certificate per FQDN, could the FQDN itself be the id? This way there's no need for the resolve endpoint. I suppose the same goes for dkim keys and domain aliases actually, so maybe that's more of a breaking change thing if you want to keep it consistent.

**Comment by andris9** [comment] 2021-05-13 20:17
I have thought about automatic certificate capabilities but it seems to me that including full featured ACME support would be a bit too much, especially if it does not help in a lot of cases (in clustered setup you probably do not have HTTP running on the same server as IMAP). As TLS certificates can be added via API then everything is still scriptable - eg. you can generate certs with your favourite ACME client and then push these certs to WildDuck using `curl`.

Regarding FQDN as the ID. The convention has been from the start to use those 24 character hex ID's to identify all resources. It might not always be the best choice, hostname in this case already is unique (there's even a unique index for it, so you can't add multiple certs even if you wanted to) but for consistency reasons I kept the same pattern as with other resources.

Adding value example is a good idea, I never realised this can be done. Added examples for all the TLS Cert API calls.

**Comment by andris9** [comment] 2021-05-14 07:40
Well, I talked with the guys from Zone and they wanted ACME and automatic certificate provisioning, so I guess I take my first point back 😄

**Comment by louis-lau** [comment] 2021-05-14 10:14
Hahahaha. I must say I kind of forgot you need port 80 or 443 pointing at wildduck to make let's encrypt work when I suggested it. Unless you use the DNS challenge, but then you can't use it for customer domains that host DNS elsewhere.

I guess you'd have to do something like proxying http://imap.*/.well-known/acme-challenge/* to wildduck in your http load balancer. If you only wanted to allow IMAP subdomains. Then redirect any other http requests for that domain to webmail.

You have any other thoughts?

> but for consistency reasons

Makes sense.

> Added examples for all the TLS Cert API calls.

😁

**Closed** 2024-03-10 01:47 UTC
Labels: future feature, no-issue-activity
