### ISSUE TITLE
LDAP or other auth method (SSO)

### ISSUE THREAD

**Issue by diansaji** [nodemailer/wildduck#184] opened 2020-03-04 00:00 UTC
Our team currently working on making an web administration page for wildduck. We stumble on integrating wildduck with user authenticating method (OpenLDAP). Could anyone give us a hint to work this out?
It would be nice if wildduck have some sort of api to point against an identity manager (LDAP, SAML, Oauth, SSO) out of the box, since it proclaim having nearly all gmail/modern mail feature.
PS: Pardon my faulty english language

**Comment by mailanetworks** [comment] 2020-03-04 00:13
Hi @diansaji 
This is something we're looking for as well.
I'll be subscribing to this issue.

Thanks,

**Comment by andris9** [comment] 2020-03-04 06:56
Well this has been in a todo list for quite some time. There is probably not going to be a specific external authentication implementation, like built in LDAP support but some kind of authentication gateway where you could implement your specific authentication yourself, kind of what I did with IMAP API (see the [OAuth2 description for using authentication server](https://github.com/andris9/imap-api#using-oauth2)).

I have some questions though:

* I assume the identity manager handles accounts so whenever someone tries to log in to WIldDuck then Identity Manager says if the account exists or not. If WildDuck has not seen this account before then it initialises it with default settings?
* What happens when a user has an account in the Identity Manager but has not logged in to WildDuck and someone tries to send mail to this account? WD has not seen this email address before and bounces it as there is no account available.
* Does the identity Manager provide email addresses or just usernames? If only usernames how should these users get addresses assigned?

**Comment by diansaji** [comment] 2020-03-25 01:16
The idea is building something like zimbra LDAP. Identity manager can keep Domain Name (DN) and anything similiar.

**Comment by jmthackett** [comment] 2020-06-19 00:20
I'm very interested in this too. My use case is wanting to integrate against another application's userdb, possibly with oauth2. I'd like the flexibility to write my own auth script that can return eg a JSON blob with specific fields to wildduck. 

>     * I assume the identity manager handles accounts so whenever someone tries to log in to WIldDuck then Identity Manager says if the account exists or not. If WildDuck has not seen this account before then it initialises it with default settings?

Default settings then letting the provider return information on eg quotas on login or user lookup. It'd be handy if there was an endpoint I could hit to say "initialise this user from the identity manager" or "update this user from the identity manager" in case I've updated quotas etc.

>     * What happens when a user has an account in the Identity Manager but has not logged in to WildDuck and someone tries to send mail to this account? WD has not seen this email address before and bounces it as there is no account available.

Split access into user validation and password validation. Dovecot does this, and it means a user doesn't have to have logged in in order to be validated as existing. Maybe leave uninitiated until an endpoint like the one above has been hit?

>     * Does the identity Manager provide email addresses or just usernames? If only usernames how should these users get addresses assigned?

I'd suggest email addresses, but I'm not fussy myself!

**Comment by azak00** [comment] 2020-07-20 13:54
I had tried to achieve this but with no luck by installing the auth-ldap plugin in Haraka. I added the plugin to haraka config file and it started up, however, ladap users were still unable to login to wilduck. 

Does it mean wildduck is yet to support LDAP auth binding?

**Comment by louis-lau** [comment] 2020-07-20 14:04
Haraka is inbound smtp, and doesn't need authentication. So that won't do you any good :)

pop3 and imap are handled by WildDuck, and outbound smtp by ZoneMTA. LDAP is not supported by WildDuck at this time, which is why the issue is still open 😁

**Comment by louis-lau** [comment] 2020-09-13 23:46
Closing as a duplicate of #105

**Closed by louis-lau** 2020-09-13 23:46 UTC
