### ISSUE TITLE
Needed to manually start Redis

### ISSUE THREAD

**Issue by roniemartinez** [nodemailer/wildduck#181] opened 2020-02-20 11:31 UTC
I installed wildduck on a DigitalOcean droplet using the `get_install.sh` script.

When I turned off the droplet to resize it, and then turned it back on, the webmail wasn't responsive anymore and returns the error: `Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details.`

I figured out it was the Redis instance and solved it by running `/etc/init.d/redis-server restart`.

It will be very useful if part of the setup scripts is making the Redis instance reload/restart automatically after restarting the servers.

**Comment by cristiness** [comment] 2020-02-24 11:56
Same issue, same server provider.

**Comment by louis-lau** [comment] 2020-09-13 23:30
Duplicate of #112

**Closed by louis-lau** 2020-09-13 23:30 UTC
Labels: duplicate
